name: PublishCharms

on:
  push:
    tags:
      - "*"

jobs:
  build-charms:
    name: "Build the charms"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: 3.1/stable
      - name: "Build the charms"
        shell: bash
        run: |
          make version
          charmcraft pack
      - name: "Upload to edge and candidate"
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
        run: |
          extension="_ubuntu-20.04-amd64_ubuntu-22.04-amd64_centos-7-amd64_centos-8-amd64.charm"

          charmcraft upload --release=edge --release=candidate slurm-exporter$extension --resource slurm-exporter:1
