name: PublishCharms

on:
  pull_request:
    types: [closed]

jobs:
  build-charms:
    name: "Build the charms"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Install charmcraft"
        run: |
          sudo snap install charmcraft --channel=latest/stable --classic
      - name: "Install lxd"
        run: |
          sudo snap install lxd --channel=latest/stable
          sudo snap refresh lxd
      - name: "Configure lxd"
        run: |
          sudo adduser $USER lxd
          newgrp lxd        
          sudo lxd init --auto
          sudo lxc network set lxdbr0 ipv6.address none        
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
      - name: "Build the charms"
        shell: bash
        run: |
          make version
          charmcraft pack

      - name: "Upload to edge"
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
        run: |
          extension="_ubuntu-20.04-amd64_ubuntu-22.04-amd64_centos-7-amd64_centos-8-amd64.charm"

          charmcraft upload --release=edge slurm-exporter$extension --resource slurm-exporter:1
