name: Lint

on: pull_request

jobs:
    lint-charm:
        name: "Run linter"
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                  python-version: '3.x'
                  architecture: 'x64'
            - name: "Install tox"
              run: |
                  pip install tox
            - name: "lint the charms"
              run: |
                  make lint

    build-charm:
        name: "Build the charms"
        needs: lint-charm
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: "Install charmcraft"
              run: |
                  sudo snap install charmcraft --channel=latest/stable --classic
            - name: "Install lxd"
              run: |
                  sudo snap install lxd --channel=latest/stable
                  sudo snap refresh lxd
            - name: "Configure lxd"
              run: |
                  sudo adduser $USER lxd
                  newgrp lxd        
                  sudo lxd init --auto
                  sudo lxc network set lxdbr0 ipv6.address none        
                  sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
            - name: "Build the charms"
              shell: bash
              run: |
                  make version
                  sg lxd -c "charmcraft pack"

                  echo "charm version: $(cat version)"
